Cart item + cart layout
fe-feb23-department-6/phone_store pull request #19
Opened 2023-06-14 17:37 UTC by ymys1

2023-06-14 20:05 UTC, roshirin requested changes

2023-06-14 20:05 UTC, roshirin commented on src/components/Cart/CartListItem/CartListItem.scss
> +  justify-content: space-between;
```suggestion

```
You have to use more complicated positioning here. Check the layout: -/+ buttons must be straight under the previous ones.

2023-06-15 12:51 UTC, ymys1 commented on src/components/Cart/Checkout/Checkout.tsx
> +      <p className="checkout__total-price">{`$${totalPrice}`}</p>
There should be $ symbol before price

2023-06-15 17:51 UTC, roshirin approved these changes

2023-06-15 20:27 UTC, merged